# Exported from Render on 2024-03-23T21:09:59Z
databases:
- name: nlp_project
  databaseName: nlp_project_sgxl
  user: nlp_project
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  - source: 10.217.255.13/32
  postgresMajorVersion: "16"
version: "1"