services:
  - type: web
    runtime: docker
    name: bot
    region: frankfurt
    plan: free
    rootDir: telegram_bot
    dockerfilePath: ./telegram_bot/Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: PORT
        value: '10000:10000'

  - type: web
    runtime: docker
    name: web
    region: frankfurt
    plan: free
    rootDir: web_service
    dockerfilePath: ./web_service/Dockerfile
    envVars:
      - key: HOST_DB
        sync: true
      - key: PORT_DB
        sync: true
      - key: USER_DB
        sync: true
      - key: PASSWORD_DB
        sync: true
      - key: NAME_DB
        sync: true
      - key: PORT
        value: '8000:8000'


databases:
- name: postgres
  databaseName: nlp_project_gmuh
  user: nlp_project_gmuh_user
  ipAllowList:
    - source: 0.0.0.0
      description: everyone

# secrets:
#   db-password:
#     file: .configs/db_password.txt

# networks:
#   nlp-project-network:
#     name: nlp-project-network
#     driver: bridge
#     attachable: true