services:
  - type: web
    runtime: docker
    name: bot
    region: frankfurt
    plan: free
    rootDir: telegram_bot
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: '10000:10000'

  - type: web
    runtime: docker
    name: web
    region: frankfurt
    plan: free
    rootDir: web_service
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST_DB
        sync: false
      - key: PORT_DB
        sync: false
      - key: USER_DB
        sync: false
      - key: PASSWORD_DB
        sync: false
      - key: NAME_DB
        sync: false
      - key: PORT
        value: '8000:8000'


# databases:
# - name: postgres
#   databaseName: nlp_project_gmuh
#   user: nlp_project_gmuh_user
#   plan: free
#   ipAllowList:
#     - source: 0.0.0.0
#       description: everyone

# secrets:
#   db-password:
#     file: .configs/db_password.txt

# networks:
#   nlp-project-network:
#     name: nlp-project-network
#     driver: bridge
#     attachable: true